#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Users log out
logout:
    path: /logout

history:
    path: /{_locale}/history
    controller: App\Controller\MainWebsiteController::history
    requirements:
         _locale: en|fr